package databaseproject;

import databaseproject.myDBCon;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

//This class creates the GUI for adding an employee, and implements all the needed
//functions in order to veryify the user input is valid, and then adds it to the db

public class AddComic extends javax.swing.JFrame {

    //instantiate a database connection
    myDBCon con = new myDBCon();

    public AddComic() {
        
        try {
            initComponents();
            // center form in screen
            this.setLocationRelativeTo(null);
            // set all error labels to invisible
            clearErrorLabels();
            
            //populate mgr and deptno combo boxes
            con.rs = con.executeStatement("SELECT name FROM publisher ORDER BY name ASC");

            // populate mgr combo box
            while (con.rs.next()) {
                System.out.println(con.rs.getString("name"));
                cmbPublisher.addItem(con.rs.getString("name"));
            }

            con.rs.close();
        } catch (SQLException ex) {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        nameError = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        HomeButton = new javax.swing.JButton();
        UsernamelLabel1 = new javax.swing.JLabel();
        ISBNText = new javax.swing.JTextField();
        ISBNError = new javax.swing.JLabel();
        priceText = new javax.swing.JTextField();
        priceError = new javax.swing.JLabel();
        UsernamelLabel2 = new javax.swing.JLabel();
        UsernamelLabel3 = new javax.swing.JLabel();
        volumeText = new javax.swing.JTextField();
        volumeError = new javax.swing.JLabel();
        UsernamelLabel4 = new javax.swing.JLabel();
        quantityError = new javax.swing.JLabel();
        quantityText = new javax.swing.JTextField();
        UsernamelLabel5 = new javax.swing.JLabel();
        publisherError = new javax.swing.JLabel();
        cmbPublisher = new javax.swing.JComboBox<>();
        UsernamelLabel6 = new javax.swing.JLabel();
        issueText = new javax.swing.JTextField();
        issueError = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Data");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add Comic");

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameLabel.setText("Name:");

        submitButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        submitButton.setText("Add Comic");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        nameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        nameError.setForeground(new java.awt.Color(255, 0, 0));
        nameError.setText("error label");

        nameText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        HomeButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/home.png"))); // NOI18N
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        UsernamelLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UsernamelLabel1.setText("ISBN:");

        ISBNText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ISBNText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISBNTextActionPerformed(evt);
            }
        });

        ISBNError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        ISBNError.setForeground(new java.awt.Color(255, 0, 0));
        ISBNError.setText("error label");

        priceText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        priceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextActionPerformed(evt);
            }
        });

        priceError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        priceError.setForeground(new java.awt.Color(255, 0, 0));
        priceError.setText("error label");

        UsernamelLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UsernamelLabel2.setText("Price:");

        UsernamelLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UsernamelLabel3.setText("Volume:");

        volumeText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        volumeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeTextActionPerformed(evt);
            }
        });

        volumeError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        volumeError.setForeground(new java.awt.Color(255, 0, 0));
        volumeError.setText("error label");

        UsernamelLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UsernamelLabel4.setText("Quantity:");

        quantityError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        quantityError.setForeground(new java.awt.Color(255, 0, 0));
        quantityError.setText("error label");

        quantityText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quantityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTextActionPerformed(evt);
            }
        });

        UsernamelLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UsernamelLabel5.setText("Publisher:");

        publisherError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        publisherError.setForeground(new java.awt.Color(255, 0, 0));
        publisherError.setText("error label");

        cmbPublisher.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbPublisher.setMaximumRowCount(100);

        UsernamelLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UsernamelLabel6.setText("Issue:");

        issueText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        issueText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueTextActionPerformed(evt);
            }
        });

        issueError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        issueError.setForeground(new java.awt.Color(255, 0, 0));
        issueError.setText("error label");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/pics/icons8-pow-50.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(UsernamelLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantityText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantityError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(submitButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(UsernamelLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(publisherError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UsernamelLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UsernamelLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UsernamelLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ISBNText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(volumeText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ISBNError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(priceError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(volumeError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(UsernamelLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(issueText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(issueError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameError)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ISBNError)
                    .addComponent(ISBNText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernamelLabel1))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceError)
                    .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernamelLabel2))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volumeError)
                    .addComponent(volumeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernamelLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issueError)
                    .addComponent(issueText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernamelLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantityError)
                            .addComponent(quantityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsernamelLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(publisherError)
                            .addComponent(UsernamelLabel5)
                            .addComponent(cmbPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(submitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //check if string is int
    public boolean isInteger(String s) {
        try {
            Long.parseLong(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }
    
    public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }
    
    //clear all error labels
    void clearErrorLabels() {
        nameError.setText("");
        ISBNError.setText("");
        priceError.setText("");
        volumeError.setText("");
        issueError.setText("");
        quantityError.setText("");
        publisherError.setText("");
                
    }
    //check if data is valid
    boolean isValidData() {

        clearErrorLabels();
        boolean result = true;
        
        if (nameText.getText().trim().isEmpty() || (nameText.getText().trim().length() > 50)) {
            if (nameText.getText().trim().isEmpty()) {
                nameError.setText("Invalid. Cannot be empty.");
            } else if (nameText.getText().trim().length() > 50) {
                nameError.setText("Invalid. Must be <= 50 chars.");
            }
            System.out.println("Name Error");
            nameError.setVisible(true);
            result = false;
        }
        
        if (ISBNText.getText().trim().isEmpty() || !isInteger(ISBNText.getText().trim()) || (ISBNText.getText().trim().length() != 13)) {
            if (ISBNText.getText().trim().isEmpty()) {
                ISBNError.setText("Invalid. Cannot be empty.");
            } else if (ISBNText.getText().trim().length() != 13) {
                ISBNError.setText("Invalid. Must be 13 integers.");
            }
            if (!isInteger(ISBNText.getText().trim())){
                ISBNError.setText("Invalid. Not an integer.");
            }
            System.out.println("ISBN Error");
            ISBNError.setVisible(true);
            result = false;
        }
        
        if (priceText.getText().trim().isEmpty() || !isDouble(priceText.getText().trim()) || (priceText.getText().trim().length() > 6)) {
            if (priceText.getText().trim().isEmpty()) {
                priceError.setText("Invalid. Cannot be empty.");
            } else if (priceText.getText().trim().length() > 6) {
                priceError.setText("Invalid. Must be < $999.99");
            }
            System.out.println("Price Error");
            priceError.setVisible(true);
            result = false;
        }
        
        if (volumeText.getText().trim().isEmpty() || !isInteger(volumeText.getText().trim()) || (volumeText.getText().trim().length() > 4)) {
            if (volumeText.getText().trim().isEmpty()) {
                volumeError.setText("Invalid. Cannot be empty.");
            } else if (volumeText.getText().trim().length() > 4) {
                volumeError.setText("Invalid. Must be < 4 integers.");
            }
            System.out.println("Volume Error");
            volumeError.setVisible(true);
            result = false;
        }
        
         if (issueText.getText().trim().isEmpty() || !isInteger(issueText.getText().trim()) || (issueText.getText().trim().length() > 4)) {
            if (issueText.getText().trim().isEmpty()) {
                issueText.setText("Invalid. Cannot be empty.");
            } else if (issueText.getText().trim().length() > 4) {
                issueError.setText("Invalid. Must be < 4 integers.");
            }
            System.out.println("Issue Error");
            issueError.setVisible(true);
            result = false;
        }
        
        if (quantityText.getText().trim().isEmpty() || !isInteger(quantityText.getText().trim()) || (quantityText.getText().trim().length() > 5)) {
            if (quantityText.getText().trim().isEmpty()) {
                quantityError.setText("Invalid. Cannot be empty.");
            } else if (quantityText.getText().trim().length() != 5) {
                quantityError.setText("Invalid. Must be < 6 integers.");
            }
            System.out.println("Quantity Error");
            quantityError.setVisible(true);
            result = false;
        }
        
        return result;
    }
    //clear all the user inputs 
    void clearInputBoxes() {
        nameText.setText("");
        ISBNText.setText("");
        priceText.setText("");
        volumeText.setText("");
        issueText.setText("");
        quantityText.setText("");
        cmbPublisher.setSelectedIndex(0);
    }

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:

        try {
            // make the result set scrolable forward/backward updatable
            if (isValidData()) {
                //if user input is valid, create SQL command to insert tuple
                String sqlCMD = "INSERT INTO COMIC VALUES (" + ISBNText.getText().trim()
                        + ",'" + priceText.getText() + "','" + nameText.getText() + "'," + volumeText.getText() + "," + issueText.getText() + "," + quantityText.getText() + ",'" + cmbPublisher.getSelectedItem() + "')";
                
                System.out.println(sqlCMD);
                
                int result = con.executePrepared(sqlCMD);
                
                if (result > 0) {
                    javax.swing.JLabel label = new javax.swing.JLabel("New comic added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    
                    clearInputBoxes();
                } else {
                    // check validation errors
                }
                
                
            } else {

                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error adding new comic\n" + e.getMessage());
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void ISBNTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISBNTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISBNTextActionPerformed

    private void priceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextActionPerformed

    private void volumeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volumeTextActionPerformed

    private void quantityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTextActionPerformed

    private void issueTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issueTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeButton;
    private javax.swing.JLabel ISBNError;
    private javax.swing.JTextField ISBNText;
    private javax.swing.JLabel UsernamelLabel1;
    private javax.swing.JLabel UsernamelLabel2;
    private javax.swing.JLabel UsernamelLabel3;
    private javax.swing.JLabel UsernamelLabel4;
    private javax.swing.JLabel UsernamelLabel5;
    private javax.swing.JLabel UsernamelLabel6;
    private javax.swing.JComboBox<String> cmbPublisher;
    private javax.swing.JLabel issueError;
    private javax.swing.JTextField issueText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nameError;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel priceError;
    private javax.swing.JTextField priceText;
    private javax.swing.JLabel publisherError;
    private javax.swing.JLabel quantityError;
    private javax.swing.JTextField quantityText;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel volumeError;
    private javax.swing.JTextField volumeText;
    // End of variables declaration//GEN-END:variables
}
