/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseproject;

/**
 *
 * @author Mohammed
 */

public class Menu extends javax.swing.JFrame {

    //Using this top pass as a parameter
    LoginUser u;
    public Menu(LoginUser luser) {
        initComponents();
        this.setLocationRelativeTo(null);
        u = luser;
        if(luser.type == 1)
        {
          jMenuAdmin.setVisible(false);
          jMenuAdmin1.setVisible(false);
          jMenuAdmin2.setVisible(false);
        }
        else{
            jMenuOrders.setVisible(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuBooks = new javax.swing.JMenu();
        jMenuItemBrowseBooks = new javax.swing.JMenuItem();
        jMenuOrders = new javax.swing.JMenu();
        jMenuItemShoppingCart = new javax.swing.JMenuItem();
        jMenuItemOrderHistory = new javax.swing.JMenuItem();
        jMenuSettings = new javax.swing.JMenu();
        jMenuItemEditInfo = new javax.swing.JMenuItem();
        jMenuAdmin = new javax.swing.JMenu();
        jMenuItemAddAdmin = new javax.swing.JMenuItem();
        jMenuItemEditUsers = new javax.swing.JMenuItem();
        jMenuAdmin1 = new javax.swing.JMenu();
        jMenuItemAddAuthor = new javax.swing.JMenuItem();
        jMenuItemAddAuthor1 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemAddBook = new javax.swing.JMenuItem();
        jMenuItemAddAuthor2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuAdmin2 = new javax.swing.JMenu();
        jMenuItemEditAuthors = new javax.swing.JMenuItem();
        jMenuItemEditPublishers = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItemEditBooks = new javax.swing.JMenuItem();
        jMenuItemEditBookAuthor = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/pics/bg (1) (1).jpeg"))); // NOI18N

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenuFile.setText("File");
        jMenuFile.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItemLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemLogout.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/logout.png"))); // NOI18N
        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemLogout);

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemExit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/close.png"))); // NOI18N
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuBooks.setText("Comics");
        jMenuBooks.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItemBrowseBooks.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemBrowseBooks.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemBrowseBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/pics/icons8-pow-50.png"))); // NOI18N
        jMenuItemBrowseBooks.setText("Browse Comics");
        jMenuItemBrowseBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBrowseBooksActionPerformed(evt);
            }
        });
        jMenuBooks.add(jMenuItemBrowseBooks);

        jMenuBar1.add(jMenuBooks);

        jMenuOrders.setText("Orders");
        jMenuOrders.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItemShoppingCart.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemShoppingCart.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemShoppingCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/Shopping cart.png"))); // NOI18N
        jMenuItemShoppingCart.setText("Shopping Cart");
        jMenuItemShoppingCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemShoppingCartActionPerformed(evt);
            }
        });
        jMenuOrders.add(jMenuItemShoppingCart);

        jMenuItemOrderHistory.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemOrderHistory.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemOrderHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/order history.png"))); // NOI18N
        jMenuItemOrderHistory.setText("Order History");
        jMenuItemOrderHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOrderHistoryActionPerformed(evt);
            }
        });
        jMenuOrders.add(jMenuItemOrderHistory);

        jMenuBar1.add(jMenuOrders);

        jMenuSettings.setText("Settings");
        jMenuSettings.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItemEditInfo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemEditInfo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemEditInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/settings.png"))); // NOI18N
        jMenuItemEditInfo.setText("Edit Information");
        jMenuItemEditInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditInfoActionPerformed(evt);
            }
        });
        jMenuSettings.add(jMenuItemEditInfo);

        jMenuBar1.add(jMenuSettings);

        jMenuAdmin.setText("Manage Users");
        jMenuAdmin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAdminActionPerformed(evt);
            }
        });

        jMenuItemAddAdmin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemAddAdmin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemAddAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/pics/Add User.png"))); // NOI18N
        jMenuItemAddAdmin.setText("Add Admin");
        jMenuItemAddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddAdminActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jMenuItemAddAdmin);

        jMenuItemEditUsers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemEditUsers.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemEditUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/edit users.png"))); // NOI18N
        jMenuItemEditUsers.setText("Edit Users");
        jMenuItemEditUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditUsersActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jMenuItemEditUsers);

        jMenuBar1.add(jMenuAdmin);

        jMenuAdmin1.setText("Add Data");
        jMenuAdmin1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuAdmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAdmin1ActionPerformed(evt);
            }
        });

        jMenuItemAddAuthor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemAddAuthor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemAddAuthor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/pics/Add User.png"))); // NOI18N
        jMenuItemAddAuthor.setText("Add Author");
        jMenuItemAddAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddAuthorActionPerformed(evt);
            }
        });
        jMenuAdmin1.add(jMenuItemAddAuthor);

        jMenuItemAddAuthor1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemAddAuthor1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemAddAuthor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/pics/Add User.png"))); // NOI18N
        jMenuItemAddAuthor1.setText("Add Publisher");
        jMenuItemAddAuthor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddAuthor1ActionPerformed(evt);
            }
        });
        jMenuAdmin1.add(jMenuItemAddAuthor1);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem1.setFont(new java.awt.Font("Sathu", 0, 24)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/pics/Add User.png"))); // NOI18N
        jMenuItem1.setText("Add Illustrator");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAdmin1.add(jMenuItem1);

        jMenuItemAddBook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemAddBook.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemAddBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/add books.png"))); // NOI18N
        jMenuItemAddBook.setText("Add Comic");
        jMenuItemAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddBookActionPerformed(evt);
            }
        });
        jMenuAdmin1.add(jMenuItemAddBook);

        jMenuItemAddAuthor2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemAddAuthor2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemAddAuthor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/add books.png"))); // NOI18N
        jMenuItemAddAuthor2.setText("Add Comic Author");
        jMenuItemAddAuthor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddAuthor2ActionPerformed(evt);
            }
        });
        jMenuAdmin1.add(jMenuItemAddAuthor2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem3.setFont(new java.awt.Font("Sathu", 0, 24)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/pics/add books.png"))); // NOI18N
        jMenuItem3.setText("Add Comic Illustrator");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuAdmin1.add(jMenuItem3);

        jMenuBar1.add(jMenuAdmin1);

        jMenuAdmin2.setText("Edit Data");
        jMenuAdmin2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuAdmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAdmin2ActionPerformed(evt);
            }
        });

        jMenuItemEditAuthors.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemEditAuthors.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemEditAuthors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/pics/edit users.png"))); // NOI18N
        jMenuItemEditAuthors.setText("Edit Authors");
        jMenuItemEditAuthors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditAuthorsActionPerformed(evt);
            }
        });
        jMenuAdmin2.add(jMenuItemEditAuthors);

        jMenuItemEditPublishers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemEditPublishers.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemEditPublishers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/pics/edit users.png"))); // NOI18N
        jMenuItemEditPublishers.setText("Edit Publishers");
        jMenuItemEditPublishers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditPublishersActionPerformed(evt);
            }
        });
        jMenuAdmin2.add(jMenuItemEditPublishers);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem2.setFont(new java.awt.Font("Sathu", 0, 24)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/pics/edit users.png"))); // NOI18N
        jMenuItem2.setText("Edit Illustrator");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuAdmin2.add(jMenuItem2);

        jMenuItemEditBooks.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemEditBooks.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemEditBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/Edit Books.png"))); // NOI18N
        jMenuItemEditBooks.setText("Edit Comic");
        jMenuItemEditBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditBooksActionPerformed(evt);
            }
        });
        jMenuAdmin2.add(jMenuItemEditBooks);

        jMenuItemEditBookAuthor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemEditBookAuthor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItemEditBookAuthor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/Edit Books.png"))); // NOI18N
        jMenuItemEditBookAuthor.setText("Edit Comic Authors");
        jMenuItemEditBookAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditBookAuthorActionPerformed(evt);
            }
        });
        jMenuAdmin2.add(jMenuItemEditBookAuthor);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem4.setFont(new java.awt.Font("Sathu", 0, 24)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/databaseproject/pics/Edit Books.png"))); // NOI18N
        jMenuItem4.setText("Edit Comic Illustrators");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuAdmin2.add(jMenuItem4);

        jMenuBar1.add(jMenuAdmin2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        // TODO add your handling code here:
        (new LoginForm()).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemBrowseBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBrowseBooksActionPerformed
        // TODO add your handling code here:
        (new BrowseComics(u)).setVisible(true);
    }//GEN-LAST:event_jMenuItemBrowseBooksActionPerformed

    private void jMenuItemShoppingCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemShoppingCartActionPerformed
        // TODO add your handling code here:
        (new ShoppingCart(u)).setVisible(true);
    }//GEN-LAST:event_jMenuItemShoppingCartActionPerformed

    private void jMenuItemEditInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditInfoActionPerformed
        // TODO add your handling code here:
        (new EditInformation(u)).setVisible(true);
    }//GEN-LAST:event_jMenuItemEditInfoActionPerformed

    private void jMenuItemEditUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditUsersActionPerformed
        // TODO add your handling code here:
        (new EditAdmin(u)).setVisible(true);
    }//GEN-LAST:event_jMenuItemEditUsersActionPerformed

    private void jMenuItemEditBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditBooksActionPerformed
        // TODO add your handling code here:
        (new EditComics(u)).setVisible(true);
    }//GEN-LAST:event_jMenuItemEditBooksActionPerformed

    private void jMenuItemOrderHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOrderHistoryActionPerformed
        // TODO add your handling code here:
        (new OrderHistory(u)).setVisible(true);
    }//GEN-LAST:event_jMenuItemOrderHistoryActionPerformed

    private void jMenuItemAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddAdminActionPerformed
        // TODO add your handling code here:
        (new AdminForm()).setVisible(true);
    }//GEN-LAST:event_jMenuItemAddAdminActionPerformed

    private void jMenuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAdminActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuAdminActionPerformed

    private void jMenuAdmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAdmin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAdmin1ActionPerformed

    private void jMenuItemAddAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddAuthorActionPerformed
        // TODO add your handling code here:
        (new AddAuthor()).setVisible(true);
    }//GEN-LAST:event_jMenuItemAddAuthorActionPerformed

    private void jMenuItemAddAuthor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddAuthor1ActionPerformed
        // TODO add your handling code here:
        (new AddPublisher()).setVisible(true);
    }//GEN-LAST:event_jMenuItemAddAuthor1ActionPerformed

    private void jMenuItemAddAuthor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddAuthor2ActionPerformed
        // TODO add your handling code here:
        (new AddComicAuthor()).setVisible(true);
    }//GEN-LAST:event_jMenuItemAddAuthor2ActionPerformed

    private void jMenuAdmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAdmin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAdmin2ActionPerformed

    private void jMenuItemEditAuthorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditAuthorsActionPerformed
        // TODO add your handling code here:
        (new EditAuthor()).setVisible(true);
    }//GEN-LAST:event_jMenuItemEditAuthorsActionPerformed

    private void jMenuItemEditPublishersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditPublishersActionPerformed
        // TODO add your handling code here:
        (new EditPublisher()).setVisible(true);
    }//GEN-LAST:event_jMenuItemEditPublishersActionPerformed

    private void jMenuItemEditBookAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditBookAuthorActionPerformed
        // TODO add your handling code here:
        (new EditComicAuthor()).setVisible(true);
    }//GEN-LAST:event_jMenuItemEditBookAuthorActionPerformed

    private void jMenuItemAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddBookActionPerformed
        // TODO add your handling code here:
        (new AddComic()).setVisible(true);
    }//GEN-LAST:event_jMenuItemAddBookActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        (new AddIllustator()).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    (new EditIllustrator()).setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    (new EditComicIllustrator()).setVisible(true);

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        (new AddComicIllustrator()).setVisible(true);

    }//GEN-LAST:event_jMenuItem3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuAdmin;
    private javax.swing.JMenu jMenuAdmin1;
    private javax.swing.JMenu jMenuAdmin2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBooks;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemAddAdmin;
    private javax.swing.JMenuItem jMenuItemAddAuthor;
    private javax.swing.JMenuItem jMenuItemAddAuthor1;
    private javax.swing.JMenuItem jMenuItemAddAuthor2;
    private javax.swing.JMenuItem jMenuItemAddBook;
    private javax.swing.JMenuItem jMenuItemBrowseBooks;
    private javax.swing.JMenuItem jMenuItemEditAuthors;
    private javax.swing.JMenuItem jMenuItemEditBookAuthor;
    private javax.swing.JMenuItem jMenuItemEditBooks;
    private javax.swing.JMenuItem jMenuItemEditInfo;
    private javax.swing.JMenuItem jMenuItemEditPublishers;
    private javax.swing.JMenuItem jMenuItemEditUsers;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemOrderHistory;
    private javax.swing.JMenuItem jMenuItemShoppingCart;
    private javax.swing.JMenu jMenuOrders;
    private javax.swing.JMenu jMenuSettings;
    // End of variables declaration//GEN-END:variables
}